apiVersion: v1
kind: Pod
metadata:
  name: nvidia-infer
spec:
  restartPolicy: Never
  containers:
  - name: infer
    image: nvcr.io/nvidia/tritonserver:24.10
    resources:
      limits:
        nvidia.com/gpu: 1
    nodeSelector:
      nvidia.com/gpu.present: "true"
