- name: Install kube packages
  apt:
    name:
      - kubelet=1.32.0-00
      - kubeadm=1.32.0-00
      - kubectl=1.32.0-00
    state: present

- name: kubeadm init
  command: >
    kubeadm init
    --pod-network-cidr=10.244.0.0/16
    --control-plane-endpoint={{ ansible_host }}:6443
  args:
    creates: /etc/kubernetes/admin.conf

- name: Copy admin.conf to ubuntu
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Install Cilium
  command: >
    kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.16/install/kubernetes/quick-install.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_cmd

- name: Set fact for workers
  set_fact:
    kube_join_cmd: "{{ join_cmd.stdout }}"
